# Python Einführung 3 - Jupyter Notebook

## Grundlagen der Cognitive Science

### Seminar - 06.12.2021

Dieses Notebook enthält Informationen und Übungsaufgaben für nützliche Libraries und Packages. Diese werden für verschiedene Programme und Anwendungen, die für uns interessant sind, genutzt und vereinfachen vieles. Entsprechender Code und Beispiele demonstrieren im Folgenden wie diese funktionieren.

Im allgemeine müssen Packages und Libraries immer zunächst eingebunden und importiert werden. Um dies zu tun wird das `import` Statement genutzt. Aus Konvention und zur Vereinfachung kann man zusätzlich Abkürzungen angeben mit denen man die entsprechend enthaltenen Funktionen aufrufen kann. Zum Beispiel ist `np` die konventionelle Abkürzung für Numpy, aber eigentlich können beliebige Abkürzungen gewählt werden.

Des Weiteren können auch nur bestimmte Methoden aus Libraries importiert werden, wenn das erwünscht ist. 

In [2]:
import numpy as np 
import scipy 
from scipy.linalg import det #importiert Methode det 

### NUMPY

Numpy ist eine library, die mathematische und numerische Funktionen und Datenstrukturen bereit stellt. Numpy ermöglicht, dass diese Funktionalitäten integriert und effizient nutzbar werden. Beispielsweise, wird es so möglich in Python mit Arrays und Matrizen effizient zu rechnen und zu arbeiten. Dies vereinfacht besonders in daten-lastigen Bereichen (Data science und scientific computing) viele Anwendungen und macht diese schneller, einfacher und übersichtlicher. 

https://numpy.org/doc/stable/

### SCIPY

SciPy ist eine Library, die auf Numpy aufbaut und dessen Leistungsfähigkeit durch weitere Funktionen, wie beispielsweise Minimierung, Regression, Fouriertransformation etc., erweitert. Scipy ist in sub-packages unterteilt, von denen auch nur entsprechend nötige importiert werden können statt alle.

https://docs.scipy.org/doc/scipy/reference/

Die Nutzung dieser - und auch anderer - Erweiterungen vereinfacht viele Dinge. Natürlich muss man aber bei der Nutzung auch einiges beachten: 

- Um zu erfahren, wie die Datenstrukturen und Funktionen genutzt werden sollen/können, sollte die bereitgestellte Dokumentation genutzt werden. 
- Innerhalb solche Packages und Libraries gibt es oft auch wieder neue Datenstrukturen die sich anders verhalten als die Basic Python Datenstrukturen die wir letztes Mal gesehen haben.
- Nutzt nur Funktionen von den ihr wisst, was sie wirklich tun (was wird da gemacht und welchen Output bekommt man)
- Es kann hilfreich sein, extra Kommentare zu den aus libraries genutzen Funktionen hinzuzufügen, wenn diese nicht direkt eindeutig durch ihren Namen erkenntlich machen, was sie tun 

### Aufgabe 1

Schreibt eine Funktion, die einen Würfelwurf simulieren kann. Der Würfel soll fair sein, d.h. alle möglichen Ereignisse (Zahlen 1,2,3,4,5,6) sollen gleich wahrscheinlich auftreten. **Hinweis:** Es gibt verschiedene Möglichkeiten, diese Aufgabe in Python mit NumPy zu lösen.

In [29]:
def cube():
    return np.random.randint(1,7)

print(cube())

4


### Aufgabe 2

Gegeben ist das mehrdimensionale NumPy Array bzw. die Matrix `mat`. Mit diesem soll in den folgenden Aufgabenteilen gearbeitet werden.

**2.0. Indizes**

Was passiert in den unten ausgeführten print Befehlen? Versuche dies zuerst direkt aus den Code zu lesen. Du kannst dann die Celle aktivieren um zu sehen ob der Ergebnis mit deine Erwartung übereinstimmt.

In [30]:
mat = np.array([[1,5,4],[3,7,9],[0,2,8]])

print(mat, '\n') # zeilenweise Ausgabe

print(mat[:,-1])  # letzte Spalte
print(mat[:,0])   # erste Spalte
print(mat[1,:])   # zweite Zeile
print(mat[0,:-1]) # erste Zeile bis zum vorletzten Element


[[1 5 4]
 [3 7 9]
 [0 2 8]] 

[4 9 8]
[1 3 0]
[3 7 9]
[1 5]


**2.1. Dimensionen**

Lasst euch die Dimensionen/Form, Größe sowie den Typ von `mat` ausgeben. **Hinweis:** Es gibt built-in Funktionen, die euch diese Werte ausgeben können.

In [35]:
print(mat.shape)
print(mat.dtype)

(3, 3)


AttributeError: 'numpy.ndarray' object has no attribute 'length'

**2.2. Einzelne Zeilen und Spalten**

Lasst euch zu erst die erste Spalte und dann die zweite Zeile von `mat` ausgeben. Lasst dann jeweils das letzte Element weg. Nutzt für diese Aufgabe die oben gezeigte Indizierung.

**2.3. Einzelne Elemente**

Ändert das letzte Element der ersten Reihe von `mat` in eine 17 und das zweite Element der letzten Spalte in eine 13.

**2.4. Erweiterung**

Erweitert `mat` indem ihr eine komplette Spalte, die nur Elmente mit dem Wert 1 enthält, ganz vorne anhängt. **Hinweis:** Beispielsweise kann hier die built-in Funktion `hstack()` hilfreich sein.

**2.5. Matrixmultiplikation**

Schreibt eine Funktion die zwei Matrizen mit einander multipliziert und dann die Ergebnismatrix zurückgibt. Erstellt hierfür eine weitere passende Matrix und multipliziert diese mit `mat`. 

**2.6. Zusammenfügen**

Fügt die für die vorherige Aufgabe neu erstellte Matrix mit `mat` zusammen. Dabei sollen die Reihen der neuen Matrix denen von `mat` folgen.

**2.7. Determinante**

Schreibt eine eigene Funktion, welche die Determinante einer 3x3 Matrix berechnen kann und diese zurückgibt. Führt diese Funktion für `mat` aus (hierunter noch mal neu definiert falls die Werte von `mat` überschrieben worden sind). Hierzu kannst du den Regel von Sarrus benutzen.

Wer Lust und Zeit hat, kann versuchen die Funktion zu veralgemeinen nach eine n x n Matrix. Dies ist eine gute Programmiererfahrung weil mann seine Funktionen oft in verschiedene Situationen einsetzen möchtte, ohne dabei mehrere Varianten definieren zu müssen. Hier wird Sarrus aber nich mehr funktionieren.

In [ ]:
# definiere deine Funktion


In [ ]:
mat = np.array([[1,5,4],[3,7,9],[0,2,8]])
# setze hierunter den Abruf nach deine Funktion

### Aufgabe 3

Schreibt eine Funktion, die testet ob das Ergebnis eurer eigenen Determinanten Funktion mit der importierten SciPy Methode `det` übereinstimmt und den entsprechenden boolschen Wert zurückgibt (es sollte True rauskommen).